//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DETAIL
    {
        public int DetailID { get; set; }
        public int ProductID { get; set; }
        public int BillID { get; set; }
        public int ProductCount { get; set; }
        public string Note { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
