//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEWS
    {
        public int Reviews1 { get; set; }
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public string Contentt { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
